In [1]:
#http://scikit-learn.org/stable/auto_examples/tree/plot_iris.html#sphx-glr-auto-examples-tree-plot-iris-py
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import pandas as pd

from sklearn import tree

In [2]:
recent = pd.read_csv("recent.csv")

/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (30,38,43,50,52,53,54,56,57,58,59,60,62,63,64,76,77,87) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
recent.columns

Index(['First name', 'Last name', 'Name', 'Conversation Rating', 'Email',
       'Phone', 'User ID', 'First Seen (MDT)', 'Signed up (MDT)',
       'Last seen (MDT)', 'Last contacted (MDT)', 'Last heard from (MDT)',
       'Web sessions', 'Country', 'Region', 'City', 'Timezone',
       'Browser Language', 'Language Override', 'Browser', 'Browser Version',
       'OS', 'Twitter Followers', 'Job Title', 'Segment', 'Tag',
       'Unsubscribed from Emails', 'Marked email as spam', 'Has hard bounced',
       'id', 'billed_in_hub', 'country', 'created_at (MDT)', 'currency',
       'description', 'avatar', 'domain', 'email', 'free',
       'last_logged_in_at (MDT)', 'login_count', 'monthly_spend', 'name',
       'needs_plan_restriction', 'orders_count', 'plan', 'products_count',
       'subdomain', 'theme', 'time_zone', 'under_maintenance',
       'unsubscribed_from_newsletter', 'using_artists', 'using_custom_domain',
       'using_custom_html', 'using_customized_order_confirmations',
       '

In [4]:
recent.shape

(109304, 98)

In [5]:
recent['using_discounts'].describe()

count     109278
unique         2
top        False
freq       79900
Name: using_discounts, dtype: object

In [6]:
y = [ 1 if x == True else 0 for x in recent['using_discounts']]

In [7]:
recent[['theme', 'plan', 'products_count', 'login_count', 'Browser','Timezone']][0:10]

theme      plan  products_count  login_count  Browser  \
0     Neat   Diamond            96.0        999.0   safari   
1     Luna  Platinum            24.0        517.0   safari   
2  Sidecar  Platinum            25.0         48.0  firefox   
3     Neat  Platinum            25.0        288.0   chrome   
4     Sexy      Gold             5.0        601.0   safari   
5     Luna  Platinum             9.0        164.0   chrome   
6     Luna      Gold             5.0        204.0   chrome   
7  Sidecar      Gold             5.0        107.0   chrome   
8  Sidecar  Platinum             2.0        109.0   chrome   
9  Sidecar  Platinum            16.0        152.0   chrome   

              Timezone  
0     America/New_York  
1  America/Los_Angeles  
2     America/New_York  
3      Asia/Phnom_Penh  
4     America/New_York  
5     America/New_York  
6     America/New_York  
7     America/New_York  
8      America/Chicago  
9      America/Chicago

In [8]:
#X = recent[['theme', 'plan', 'products_count', 'login_count', 'Browser','Timezone']]
X = recent[['products_count', 'login_count']]

In [9]:
X = pd.concat([X, pd.get_dummies(recent['theme']),pd.get_dummies(recent['plan']),
               pd.get_dummies(recent['Browser']),pd.get_dummies(recent['Timezone'])],
             axis=1)

In [10]:
X = X.fillna(0)

In [11]:
X.columns

Index(['products_count', 'login_count', 'Big Cartel Shop', 'Blocks', 'Foundry',
       'Good Vibes', 'Luna', 'Lunch Break', 'Neat', 'Nova',
       ...
       'Pacific/Auckland', 'Pacific/Chatham', 'Pacific/Fiji', 'Pacific/Guam',
       'Pacific/Honolulu', 'Pacific/Noumea', 'Pacific/Port_Moresby',
       'Pacific/Saipan', 'Pacific/Samoa', 'US/Samoa'],
      dtype='object', length=266)

In [12]:
clf = tree.DecisionTreeClassifier().fit(X, y)

In [14]:
clf.score(X,y)

0.99474859108541314

In [15]:
clf.tree_.max_depth

56

In [16]:
clf2 = tree.DecisionTreeClassifier(max_depth=20).fit(X, y)

In [17]:
clf2.score(X,y)

0.91351643123764914

In [18]:
X.ix[0:3]

products_count  login_count  Big Cartel Shop  Blocks  Foundry  Good Vibes  \
0            96.0        999.0                0       0        0           0   
1            24.0        517.0                0       0        0           0   
2            25.0         48.0                0       0        0           0   
3            25.0        288.0                0       0        0           0   

   Luna  Lunch Break  Neat  Nova    ...     Pacific/Auckland  Pacific/Chatham  \
0     0            0     1     0    ...                    0                0   
1     1            0     0     0    ...                    0                0   
2     0            0     0     0    ...                    0                0   
3     0            0     1     0    ...                    0                0   

   Pacific/Fiji  Pacific/Guam  Pacific/Honolulu  Pacific/Noumea  \
0             0             0                 0               0   
1             0             0                 0               0   
2             0             0                 0               0   
3             0             0                 0               0   

   Pacific/Port_Moresby  Pacific/Saipan  Pacific/Samoa  US/Samoa  
0                     0               0              0         0  
1                     0               0              0         0  
2                     0               0              0         0  
3                     0               0              0         0  

[4 rows x 266 columns]

In [19]:
Xtrain = X.ix[0:30000]

In [20]:
Xtest =X.ix[30000:]

In [21]:
ytrain = y[0:30001] #wtf pandas. WHAT. THE. F

In [22]:
ytest = y[30000:]

In [23]:
clf3 = tree.DecisionTreeClassifier(max_depth=20).fit(Xtrain, ytrain)

In [24]:
clf3.score(Xtrain, ytrain)

0.94656844771840942

In [25]:
clf3.score(Xtest, ytest)

0.82864672652073035

In [26]:
import pydotplus 

In [27]:
tree.export_graphviz(clf3, out_file="clf_discount.dot", 
                         feature_names=X.columns,  
                         filled=True, rounded=True)
# pause to look at terrifying pdf

In [34]:
clf.feature_importances_

array([  5.23761902e-01,   2.09428215e-01,   0.00000000e+00,
         9.51285575e-04,   4.68532307e-03,   3.21155296e-03,
         1.09214779e-02,   1.02421895e-02,   9.15089385e-03,
         3.67829370e-03,   3.93968310e-03,   4.52972670e-03,
         3.58347872e-03,   6.41800979e-03,   2.19703707e-03,
         4.11349610e-03,   4.50800534e-03,   2.79032745e-02,
         3.44109972e-03,   1.60308918e-03,   5.64767312e-05,
         0.00000000e+00,   1.42396085e-02,   5.42834953e-03,
         7.40807427e-03,   4.79330691e-03,   0.00000000e+00,
         3.32851821e-04,   0.00000000e+00,   0.00000000e+00,
         1.34845238e-02,   0.00000000e+00,   0.00000000e+00,
         3.38215788e-05,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   3.11429501e-05,
         2.85846639e-04,   5.95061482e-05,   1.67689529e-05,
         0.00000000e+00,   0.00000000e+00,   1.43622315e-04,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,

In [28]:
clf3.feature_importances_.argmax()

0

In [29]:
#http://stackoverflow.com/questions/6910641/how-to-get-indices-of-n-maximum-values-in-a-numpy-array
ind = np.argpartition(clf3.feature_importances_, -10)[-10:]

In [30]:
#http://stackoverflow.com/questions/6771428/most-efficient-way-to-reverse-a-numpy-array
ind2 = np.flipud(ind[np.argsort(clf3.feature_importances_[ind])])

In [31]:
ind2

array([  0,   1,  17,  30,  22, 106,   6, 222,  95,   8])

In [32]:
X.columns[ind2]

Index(['products_count', 'login_count', 'Gold', 'safari', 'chrome',
       'America/New_York', 'Luna', 'Europe/London', 'America/Los_Angeles',
       'Neat'],
      dtype='object')

In [33]:
clf3.feature_importances_[ind2]

array([ 0.59730929,  0.17682487,  0.03422163,  0.01046997,  0.01025197,
        0.01020831,  0.00884802,  0.00847218,  0.00804267,  0.00763976])